dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: oQCnDPS+WGDV7wjnkMZJ203k0CGjiVUfxh0vVjUoWU+nFQs07ZG7Ymy4HCu7WdytfSDDxUpETH467dLfZsrTKe9gJfBhH9UNY2M/u0WaPtX2ZhIE27LhDzxgeZP6vcSxCkJygFV6d7UYy2cT9I5pdMivQUj2pLnciOaLPYHgG37IjjuBzxYLoEK3UauuZgEKde2cVh1TvzgjYLh8ZJn77lbnhY2fJX/rBKPOfcNrVYAcFFEKtxjPlWwYWcAHebNgoGw9KRcVYw6abbmD8WUnYYSRXE2v8Snxwws7tnUm7vH9QPUtzB99f3Cfcg7YYiqIr7sMC7wgySiuEcGeaJa544GhTGSk6LBbf2GfPo16GzAqNWQuVE6uPeaombC9/+p1rqkJqjF4Nq4UsvfEAUqzwCdosalKax9VVstxMJb9udWSqrX/px7JG5WIKWcPrt2ymngtYgAO+30A1UtZaP5KilCJACiRlbx7bcnruxnD54JQpvk5nI4hBhtBF89663nNuYhfTALIZr+rnKQkWvK5iEQHNxp6DColo+QvX6Qx0NfEQBWeFXCenZswQRlfbr14PtfPNDCzbeksh5sC4s+GDSmhwSPYFjLFOSX8GRzdKf02FX1eY8zj3EBLPF5UWx6dxcQDLvSKcxv3llwgeQIpjf/83gl4TyyFY3T1dE0M/7g=
